Cross-site Scripting in Codeigniter4/framework
418sec/huntr pull request #1234
Opened 2020-11-20 05:52 UTC by nikkolai14

## ✍️ Description

CodeIgniter is a PHP full-stack web framework that is light, fast, flexible, and secure.

This package is vulnerable to Cross-site scripting and can be exploited by bypassing the strip_image_tags function filter.

## 🕵️‍♂️ Proof of Concept

1. Install via composer by following this (link)[https://codeigniter.com/user_guide/installation/installing_composer.html]
2. Update the index method code on `app/Controllers/Home.php`
```
helper('security');

$payload = 'http://www.example.com/x" onerror=alert(1)//';
$imageurl = strip_image_tags($payload);
echo '<img src="'.$imageurl.'">';
```
3. Run the app to verify the vulnerability by following this (link)[https://codeigniter.com/user_guide/installation/running.html#local-development-server]

## 💥 Impact

The attacker can inject any malicious script on the users browser

## ☎️ Contact

Nope

## ✅ Checklist

**In my pull request, I have:**

- [x] _Created and populated the `README.md` and `vulnerability.json` files_
- [x] _Provided the repository URL and any applicable [permalinks]([https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files](https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files))_
- [x] _Defined all the applicable weaknesses ([CWEs]([https://cwe.mitre.org/](https://cwe.mitre.org/)))_
- [x] _Proposed the CVSS vector items i.e. User Interaction, Attack Complexity_
- [x] _Checked that the vulnerability affects the latest version of the package released_
- [x] _Checked that a fix does not currently exist that remediates this vulnerability_
- [x] _Complied with all applicable laws_

2020-11-20 05:54 UTC, nikkolai14 commented
[Here](https://codeigniter.com/user_guide/helpers/security_helper.html#strip_image_tags) is the explanation about that function

2020-11-20 10:03 UTC, Mik317 requested changes
Hi @nikkolai14 :smile:,
in this case I think this function doesn't work in that way.
It's used to sanitize and **strip** `img` tags, which in the example you made weren't provided.
As you can see here: https://www.tutorialandexample.com/codeigniter-security-helper/ , the `input` to be passed is the `<img src="...">` HTML tag, and probably this function is made for `editors` which automatically generate a `img` tag when a `link` to `jpeg/jpg/png` files is pasted .

The following PoC which uses the function as mentioned returns a safe `link`:

```php
$payload = 'http://www.example.com/x" onerror=alert(1)//';
echo strip_image_tags('<img src="'.$payload.'">');
// returned: http://www.example.com/x
```

Cheers,
Mik

2020-11-20 10:09 UTC, nikkolai14 commented
Hi mik,

Thanks for pointing that out, the doc is not clear, I forgot to check for
other docs.

Best,
Nikko

On Fri, Nov 20, 2020, 18:03 Michele Romano, <notifications@github.com>
wrote:

> *@Mik317* requested changes on this pull request.
>
> Hi @nikkolai14 <https://github.com/nikkolai14> 😄,
> in this case I think this function doesn't work in that way.
> It's used to sanitize and *strip* img tags, which in the example you made
> weren't provided.
> As you can see here:
> https://www.tutorialandexample.com/codeigniter-security-helper/ , the
> input to be passed is the <img src="..."> HTML tag, and probably this
> function is made for editors which automatically generate a img tag when
> a link to jpeg/jpg/png files is pasted .
>
> The following PoC which uses the function as mentioned returns a safe link
> :
>
> $payload = 'http://www.example.com/x" onerror=alert(1)//';
> echo strip_image_tags('<img src="'.$payload.'">');
> // returned: http://www.example.com/x
>
> Cheers,
> Mik
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/418sec/huntr/pull/1234#pullrequestreview-535287718>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGQML5XCH5YOUHYXKE35S4TSQY5IRANCNFSM4T4KUDLQ>
> .
>

2020-11-23 12:28 UTC, JamieSlome commented
Closing as disclosure appears invalid.

Thanks for the effort @nikkolai14! 🍰

2020-11-23 12:28 UTC, closed without merging