Cross-Site Scripting (XSS) in viser-react
418sec/huntr pull request #1336
Opened 2020-12-09 15:11 UTC by ready-research

## ✍️ Description

`viser-react` is vulnerable to `Cross-Site Scripting (XSS)`.

## 🕵️‍♂️ Proof of Concept

# Steps To Reproduce-:  

1. Install the package with `npm i viser-react` try the live demo here https://viserjs.github.io/demo.html#/viser/pie/basic-pie
2. We can edit using any of the 3 editors(React--current editor)
3. Edit any of the item field in sourceData and add the payload `<img src=x onerror=alert(1)>`. Sample code ex: `{ item: 'A"<img src=x onerror=alert(1)>', count: 40 },`
4. Click on Run -> XSS payload will get executed.

![viser-react1](https://user-images.githubusercontent.com/72916209/101647520-d2a07500-3a5e-11eb-8299-51b28c490c71.PNG)

## 💥 Impact

The attacker could trick the user and execute the javascript in his browser session stealing his session information.

## ✅ Checklist

**In my pull request, I have:**

- [x] _Created and populated the `README.md` and `vulnerability.json` files_
- [x] _Provided the repository URL and any applicable [permalinks]([https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files](https://help.github.com/en/github/managing-files-in-a-repository/getting-permanent-links-to-files))_
- [x] _Defined all the applicable weaknesses ([CWEs]([https://cwe.mitre.org/](https://cwe.mitre.org/)))_
- [x] _Proposed the CVSS vector items i.e. User Interaction, Attack Complexity_
- [x] _Checked that the vulnerability affects the latest version of the package released_
- [x] _Checked that a fix does not currently exist that remediates this vulnerability_
- [x] _Complied with all applicable laws_

2020-12-14 14:00 UTC, JamieSlome commented
@ready-research - can you clarify whether this affects this package uniquely or is being affected by some parent package for which this is a wrapper for.

Cheers! 🍰

2020-12-14 14:07 UTC, ready-research commented
@JamieSlome In the demo example it's only importing "viser-react" not any of its parent package
![image](https://user-images.githubusercontent.com/72916209/102090449-7f099f00-3e43-11eb-89a5-322943c690d1.png)

2020-12-21 10:02 UTC, adam-nygate commented
@ready-research `viser-react` is dependant upon `viser` which looks like it could be the location of the root vulnerability. Can you please check this?

2020-12-21 10:02 UTC, adam-nygate requested changes
@ready-research viser-react is dependant upon viser which looks like it could be the location of the root vulnerability. Can you please check this?

2020-12-22 07:51 UTC, closed without merging