Mass account creation   traduora (updated)
418sec/huntr pull request #842
Opened 2020-10-28 15:01 UTC by Anon-Artist

# Description
Massive account creation chained with Session fixation in traduora.
# Proof of Concept 
1. setup traduora to reproduce the vulnerability 
2. go to create an account page http://localhost:8080/signup
3. Append a Name, Email Address and Password and capture the request with Burpsuite 
4. Send the request to intruder and provide the necessary option and attack
For testing I used battering ram mode and created admin1 to admin50 with email admin1@hunt.com to admin50@hunt.com
* https://drive.google.com/file/d/1QzjQmYBBOSUB4G5pEtI34tqQEd2meKlo/view?usp=sharing
Traduora is also vulnerable to session fixation issue due to that once attacker registerd the accounts after that victim opens his account with new password the seesion of the attacker will not expired.
# Impact
Able to Create multiple accounts with a single request to annoy legit users that user with this email already exist and attacker is able to maintain access with old sessions even if the security of the account is updated by the victim.

2020-10-28 15:03 UTC, Anon-Artist commented
@JamieSlome i had created a new branch as you suggested.
I think every conflicts were solved now
Thankyou

2020-10-28 22:12 UTC, JamieSlome requested changes
Please refer to the requested changes - cheers! 🍰

2020-10-28 22:12 UTC, JamieSlome commented on bounties/other/traduora/2/vulnerability.json
> +    "PackPackageVulnerabilityID":"2",
Spelling mistake here!

2020-10-29 09:41 UTC, JamieSlome commented on bounties/other/traduora/2/vulnerability.json
> +    "Summary": "Massive account creation",
Can you change to `Mass Account Creation`?

2020-10-29 09:41 UTC, JamieSlome commented on bounties/other/traduora/2/vulnerability.json
> +            "Description": "Massive account creation is chained with session fixation"
Change to `Mass Account Creation` 🍰

2020-10-29 14:24 UTC, Anon-Artist reviewed
Updated @JamieSlome

2020-10-29 14:25 UTC, Anon-Artist reviewed
Done :+1:

2020-11-02 10:16 UTC, merged